// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dnlopes/overseer/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAgentStatusDetector creates a new instance of MockAgentStatusDetector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentStatusDetector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentStatusDetector {
	mock := &MockAgentStatusDetector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgentStatusDetector is an autogenerated mock type for the AgentStatusDetector type
type MockAgentStatusDetector struct {
	mock.Mock
}

type MockAgentStatusDetector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentStatusDetector) EXPECT() *MockAgentStatusDetector_Expecter {
	return &MockAgentStatusDetector_Expecter{mock: &_m.Mock}
}

// AgentType provides a mock function for the type MockAgentStatusDetector
func (_mock *MockAgentStatusDetector) AgentType() domain.AgentType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AgentType")
	}

	var r0 domain.AgentType
	if returnFunc, ok := ret.Get(0).(func() domain.AgentType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(domain.AgentType)
	}
	return r0
}

// MockAgentStatusDetector_AgentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentType'
type MockAgentStatusDetector_AgentType_Call struct {
	*mock.Call
}

// AgentType is a helper method to define mock.On call
func (_e *MockAgentStatusDetector_Expecter) AgentType() *MockAgentStatusDetector_AgentType_Call {
	return &MockAgentStatusDetector_AgentType_Call{Call: _e.mock.On("AgentType")}
}

func (_c *MockAgentStatusDetector_AgentType_Call) Run(run func()) *MockAgentStatusDetector_AgentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgentStatusDetector_AgentType_Call) Return(agentType domain.AgentType) *MockAgentStatusDetector_AgentType_Call {
	_c.Call.Return(agentType)
	return _c
}

func (_c *MockAgentStatusDetector_AgentType_Call) RunAndReturn(run func() domain.AgentType) *MockAgentStatusDetector_AgentType_Call {
	_c.Call.Return(run)
	return _c
}

// Detect provides a mock function for the type MockAgentStatusDetector
func (_mock *MockAgentStatusDetector) Detect(ctx context.Context, session domain.Session) (domain.AgentStatus, error) {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Detect")
	}

	var r0 domain.AgentStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Session) (domain.AgentStatus, error)); ok {
		return returnFunc(ctx, session)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Session) domain.AgentStatus); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Get(0).(domain.AgentStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Session) error); ok {
		r1 = returnFunc(ctx, session)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentStatusDetector_Detect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detect'
type MockAgentStatusDetector_Detect_Call struct {
	*mock.Call
}

// Detect is a helper method to define mock.On call
//   - ctx context.Context
//   - session domain.Session
func (_e *MockAgentStatusDetector_Expecter) Detect(ctx interface{}, session interface{}) *MockAgentStatusDetector_Detect_Call {
	return &MockAgentStatusDetector_Detect_Call{Call: _e.mock.On("Detect", ctx, session)}
}

func (_c *MockAgentStatusDetector_Detect_Call) Run(run func(ctx context.Context, session domain.Session)) *MockAgentStatusDetector_Detect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Session
		if args[1] != nil {
			arg1 = args[1].(domain.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentStatusDetector_Detect_Call) Return(agentStatus domain.AgentStatus, err error) *MockAgentStatusDetector_Detect_Call {
	_c.Call.Return(agentStatus, err)
	return _c
}

func (_c *MockAgentStatusDetector_Detect_Call) RunAndReturn(run func(ctx context.Context, session domain.Session) (domain.AgentStatus, error)) *MockAgentStatusDetector_Detect_Call {
	_c.Call.Return(run)
	return _c
}
