// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dnlopes/overseer/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProjectRepository creates a new instance of MockProjectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectRepository {
	mock := &MockProjectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectRepository is an autogenerated mock type for the ProjectRepository type
type MockProjectRepository struct {
	mock.Mock
}

type MockProjectRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectRepository) EXPECT() *MockProjectRepository_Expecter {
	return &MockProjectRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProjectRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProjectRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockProjectRepository_Delete_Call {
	return &MockProjectRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockProjectRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProjectRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectRepository_Delete_Call) Return(err error) *MockProjectRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockProjectRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) Get(ctx context.Context, id uuid.UUID) (domain.Project, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Project, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Project); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProjectRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProjectRepository_Expecter) Get(ctx interface{}, id interface{}) *MockProjectRepository_Get_Call {
	return &MockProjectRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockProjectRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProjectRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectRepository_Get_Call) Return(project domain.Project, err error) *MockProjectRepository_Get_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockProjectRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Project, error)) *MockProjectRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPath provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) GetByPath(ctx context.Context, path string) (domain.Project, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for GetByPath")
	}

	var r0 domain.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Project, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Project); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Get(0).(domain.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectRepository_GetByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPath'
type MockProjectRepository_GetByPath_Call struct {
	*mock.Call
}

// GetByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockProjectRepository_Expecter) GetByPath(ctx interface{}, path interface{}) *MockProjectRepository_GetByPath_Call {
	return &MockProjectRepository_GetByPath_Call{Call: _e.mock.On("GetByPath", ctx, path)}
}

func (_c *MockProjectRepository_GetByPath_Call) Run(run func(ctx context.Context, path string)) *MockProjectRepository_GetByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectRepository_GetByPath_Call) Return(project domain.Project, err error) *MockProjectRepository_GetByPath_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockProjectRepository_GetByPath_Call) RunAndReturn(run func(ctx context.Context, path string) (domain.Project, error)) *MockProjectRepository_GetByPath_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) List(ctx context.Context) ([]domain.Project, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Project, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Project); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockProjectRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProjectRepository_Expecter) List(ctx interface{}) *MockProjectRepository_List_Call {
	return &MockProjectRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockProjectRepository_List_Call) Run(run func(ctx context.Context)) *MockProjectRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProjectRepository_List_Call) Return(projects []domain.Project, err error) *MockProjectRepository_List_Call {
	_c.Call.Return(projects, err)
	return _c
}

func (_c *MockProjectRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Project, error)) *MockProjectRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) Save(ctx context.Context, p domain.Project) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Project) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockProjectRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Project
func (_e *MockProjectRepository_Expecter) Save(ctx interface{}, p interface{}) *MockProjectRepository_Save_Call {
	return &MockProjectRepository_Save_Call{Call: _e.mock.On("Save", ctx, p)}
}

func (_c *MockProjectRepository_Save_Call) Run(run func(ctx context.Context, p domain.Project)) *MockProjectRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Project
		if args[1] != nil {
			arg1 = args[1].(domain.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectRepository_Save_Call) Return(err error) *MockProjectRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectRepository_Save_Call) RunAndReturn(run func(ctx context.Context, p domain.Project) error) *MockProjectRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
