// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dnlopes/overseer/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAgentStatusDetectorRegistry creates a new instance of MockAgentStatusDetectorRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentStatusDetectorRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentStatusDetectorRegistry {
	mock := &MockAgentStatusDetectorRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgentStatusDetectorRegistry is an autogenerated mock type for the AgentStatusDetectorRegistry type
type MockAgentStatusDetectorRegistry struct {
	mock.Mock
}

type MockAgentStatusDetectorRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentStatusDetectorRegistry) EXPECT() *MockAgentStatusDetectorRegistry_Expecter {
	return &MockAgentStatusDetectorRegistry_Expecter{mock: &_m.Mock}
}

// DetectorFor provides a mock function for the type MockAgentStatusDetectorRegistry
func (_mock *MockAgentStatusDetectorRegistry) DetectorFor(agentType domain.AgentType) (domain.AgentStatusDetector, bool) {
	ret := _mock.Called(agentType)

	if len(ret) == 0 {
		panic("no return value specified for DetectorFor")
	}

	var r0 domain.AgentStatusDetector
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(domain.AgentType) (domain.AgentStatusDetector, bool)); ok {
		return returnFunc(agentType)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.AgentType) domain.AgentStatusDetector); ok {
		r0 = returnFunc(agentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.AgentStatusDetector)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(domain.AgentType) bool); ok {
		r1 = returnFunc(agentType)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockAgentStatusDetectorRegistry_DetectorFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetectorFor'
type MockAgentStatusDetectorRegistry_DetectorFor_Call struct {
	*mock.Call
}

// DetectorFor is a helper method to define mock.On call
//   - agentType domain.AgentType
func (_e *MockAgentStatusDetectorRegistry_Expecter) DetectorFor(agentType interface{}) *MockAgentStatusDetectorRegistry_DetectorFor_Call {
	return &MockAgentStatusDetectorRegistry_DetectorFor_Call{Call: _e.mock.On("DetectorFor", agentType)}
}

func (_c *MockAgentStatusDetectorRegistry_DetectorFor_Call) Run(run func(agentType domain.AgentType)) *MockAgentStatusDetectorRegistry_DetectorFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.AgentType
		if args[0] != nil {
			arg0 = args[0].(domain.AgentType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentStatusDetectorRegistry_DetectorFor_Call) Return(agentStatusDetector domain.AgentStatusDetector, b bool) *MockAgentStatusDetectorRegistry_DetectorFor_Call {
	_c.Call.Return(agentStatusDetector, b)
	return _c
}

func (_c *MockAgentStatusDetectorRegistry_DetectorFor_Call) RunAndReturn(run func(agentType domain.AgentType) (domain.AgentStatusDetector, bool)) *MockAgentStatusDetectorRegistry_DetectorFor_Call {
	_c.Call.Return(run)
	return _c
}
