// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAgentLauncher creates a new instance of MockAgentLauncher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentLauncher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentLauncher {
	mock := &MockAgentLauncher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgentLauncher is an autogenerated mock type for the AgentLauncher type
type MockAgentLauncher struct {
	mock.Mock
}

type MockAgentLauncher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentLauncher) EXPECT() *MockAgentLauncher_Expecter {
	return &MockAgentLauncher_Expecter{mock: &_m.Mock}
}

// Launch provides a mock function for the type MockAgentLauncher
func (_mock *MockAgentLauncher) Launch(ctx context.Context, harness string, workdir string) (int, error) {
	ret := _mock.Called(ctx, harness, workdir)

	if len(ret) == 0 {
		panic("no return value specified for Launch")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int, error)); ok {
		return returnFunc(ctx, harness, workdir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int); ok {
		r0 = returnFunc(ctx, harness, workdir)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, harness, workdir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentLauncher_Launch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Launch'
type MockAgentLauncher_Launch_Call struct {
	*mock.Call
}

// Launch is a helper method to define mock.On call
//   - ctx context.Context
//   - harness string
//   - workdir string
func (_e *MockAgentLauncher_Expecter) Launch(ctx interface{}, harness interface{}, workdir interface{}) *MockAgentLauncher_Launch_Call {
	return &MockAgentLauncher_Launch_Call{Call: _e.mock.On("Launch", ctx, harness, workdir)}
}

func (_c *MockAgentLauncher_Launch_Call) Run(run func(ctx context.Context, harness string, workdir string)) *MockAgentLauncher_Launch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAgentLauncher_Launch_Call) Return(pid int, err error) *MockAgentLauncher_Launch_Call {
	_c.Call.Return(pid, err)
	return _c
}

func (_c *MockAgentLauncher_Launch_Call) RunAndReturn(run func(ctx context.Context, harness string, workdir string) (int, error)) *MockAgentLauncher_Launch_Call {
	_c.Call.Return(run)
	return _c
}
