// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dnlopes/overseer/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAgentActivityProvider creates a new instance of MockAgentActivityProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentActivityProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentActivityProvider {
	mock := &MockAgentActivityProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgentActivityProvider is an autogenerated mock type for the AgentActivityProvider type
type MockAgentActivityProvider struct {
	mock.Mock
}

type MockAgentActivityProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentActivityProvider) EXPECT() *MockAgentActivityProvider_Expecter {
	return &MockAgentActivityProvider_Expecter{mock: &_m.Mock}
}

// Observe provides a mock function for the type MockAgentActivityProvider
func (_mock *MockAgentActivityProvider) Observe(ctx context.Context, ref domain.AgentSessionRef) (domain.AgentActivity, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Observe")
	}

	var r0 domain.AgentActivity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AgentSessionRef) (domain.AgentActivity, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AgentSessionRef) domain.AgentActivity); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		r0 = ret.Get(0).(domain.AgentActivity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.AgentSessionRef) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentActivityProvider_Observe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Observe'
type MockAgentActivityProvider_Observe_Call struct {
	*mock.Call
}

// Observe is a helper method to define mock.On call
//   - ctx context.Context
//   - ref domain.AgentSessionRef
func (_e *MockAgentActivityProvider_Expecter) Observe(ctx interface{}, ref interface{}) *MockAgentActivityProvider_Observe_Call {
	return &MockAgentActivityProvider_Observe_Call{Call: _e.mock.On("Observe", ctx, ref)}
}

func (_c *MockAgentActivityProvider_Observe_Call) Run(run func(ctx context.Context, ref domain.AgentSessionRef)) *MockAgentActivityProvider_Observe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AgentSessionRef
		if args[1] != nil {
			arg1 = args[1].(domain.AgentSessionRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentActivityProvider_Observe_Call) Return(agentActivity domain.AgentActivity, err error) *MockAgentActivityProvider_Observe_Call {
	_c.Call.Return(agentActivity, err)
	return _c
}

func (_c *MockAgentActivityProvider_Observe_Call) RunAndReturn(run func(ctx context.Context, ref domain.AgentSessionRef) (domain.AgentActivity, error)) *MockAgentActivityProvider_Observe_Call {
	_c.Call.Return(run)
	return _c
}
