// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTmuxAdapter creates a new instance of MockTmuxAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTmuxAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTmuxAdapter {
	mock := &MockTmuxAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTmuxAdapter is an autogenerated mock type for the TmuxAdapter type
type MockTmuxAdapter struct {
	mock.Mock
}

type MockTmuxAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTmuxAdapter) EXPECT() *MockTmuxAdapter_Expecter {
	return &MockTmuxAdapter_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockTmuxAdapter
func (_mock *MockTmuxAdapter) CreateSession(ctx context.Context, name string) (string, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxAdapter_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockTmuxAdapter_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTmuxAdapter_Expecter) CreateSession(ctx interface{}, name interface{}) *MockTmuxAdapter_CreateSession_Call {
	return &MockTmuxAdapter_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, name)}
}

func (_c *MockTmuxAdapter_CreateSession_Call) Run(run func(ctx context.Context, name string)) *MockTmuxAdapter_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxAdapter_CreateSession_Call) Return(tmuxID string, err error) *MockTmuxAdapter_CreateSession_Call {
	_c.Call.Return(tmuxID, err)
	return _c
}

func (_c *MockTmuxAdapter_CreateSession_Call) RunAndReturn(run func(ctx context.Context, name string) (string, error)) *MockTmuxAdapter_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// KillSession provides a mock function for the type MockTmuxAdapter
func (_mock *MockTmuxAdapter) KillSession(ctx context.Context, tmuxID string) error {
	ret := _mock.Called(ctx, tmuxID)

	if len(ret) == 0 {
		panic("no return value specified for KillSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tmuxID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxAdapter_KillSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KillSession'
type MockTmuxAdapter_KillSession_Call struct {
	*mock.Call
}

// KillSession is a helper method to define mock.On call
//   - ctx context.Context
//   - tmuxID string
func (_e *MockTmuxAdapter_Expecter) KillSession(ctx interface{}, tmuxID interface{}) *MockTmuxAdapter_KillSession_Call {
	return &MockTmuxAdapter_KillSession_Call{Call: _e.mock.On("KillSession", ctx, tmuxID)}
}

func (_c *MockTmuxAdapter_KillSession_Call) Run(run func(ctx context.Context, tmuxID string)) *MockTmuxAdapter_KillSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxAdapter_KillSession_Call) Return(err error) *MockTmuxAdapter_KillSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxAdapter_KillSession_Call) RunAndReturn(run func(ctx context.Context, tmuxID string) error) *MockTmuxAdapter_KillSession_Call {
	_c.Call.Return(run)
	return _c
}
