// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dnlopes/overseer/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSessionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockSessionRepository_Delete_Call {
	return &MockSessionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSessionRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSessionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Delete_Call) Return(err error) *MockSessionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockSessionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Get(ctx context.Context, id uuid.UUID) (domain.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSessionRepository_Expecter) Get(ctx interface{}, id interface{}) *MockSessionRepository_Get_Call {
	return &MockSessionRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockSessionRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSessionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Get_Call) Return(session domain.Session, err error) *MockSessionRepository_Get_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Session, error)) *MockSessionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) List(ctx context.Context) ([]domain.Session, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Session, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Session); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSessionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionRepository_Expecter) List(ctx interface{}) *MockSessionRepository_List_Call {
	return &MockSessionRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockSessionRepository_List_Call) Run(run func(ctx context.Context)) *MockSessionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionRepository_List_Call) Return(sessions []domain.Session, err error) *MockSessionRepository_List_Call {
	_c.Call.Return(sessions, err)
	return _c
}

func (_c *MockSessionRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Session, error)) *MockSessionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Save(ctx context.Context, s domain.Session) error {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Session) error); ok {
		r0 = returnFunc(ctx, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockSessionRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - s domain.Session
func (_e *MockSessionRepository_Expecter) Save(ctx interface{}, s interface{}) *MockSessionRepository_Save_Call {
	return &MockSessionRepository_Save_Call{Call: _e.mock.On("Save", ctx, s)}
}

func (_c *MockSessionRepository_Save_Call) Run(run func(ctx context.Context, s domain.Session)) *MockSessionRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Session
		if args[1] != nil {
			arg1 = args[1].(domain.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Save_Call) Return(err error) *MockSessionRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Save_Call) RunAndReturn(run func(ctx context.Context, s domain.Session) error) *MockSessionRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
